---
title: ""
author: Michael McLaren
date: "`r Sys.Date()`"
---


```{r setup, include=FALSE}
knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
# Global chunk options
knitr::opts_chunk$set(
  cache = TRUE, autodep = TRUE, cache.comments = FALSE,
  include = FALSE, echo = FALSE,
  warning = TRUE, message = FALSE, 
  fig.width = 7, fig.height = 7,
  fig.align = "center"
)
```

<!-- Setup -->

```{r}
library(here)
library(tidyverse)
library(speedyseq)

library(kableExtra)

library(cowplot)
library(patchwork)
library(ggbeeswarm)
devtools::load_all("~/research/r-packages/metacal")

theme_set(theme_cowplot())
```

```{r}
my_psmelt <- function(physeq) {
  speedyseq::psmelt(physeq, as = "tibble") %>%
    rename(taxon = OTU, sample = Sample, abundance = Abundance)
}
as_tibble.sample_data <- function(x) {
  x %>% as("data.frame") %>% as_tibble(rownames = "sample")
}
as_tibble.taxonomyTable <- function(x) {
  x %>% as("matrix") %>% as_tibble(rownames = "taxon")
}
```

```{r}
ps <- readRDS(here("output/phyloseq", "2020-09-12-phyloseq-focal-strains.Rds"))
ps
sam <- sample_data(ps) %>% as_tibble
tax <- tax_table(ps) %>% as_tibble %>% select(-strain_group)
tree <- phy_tree(ps)
```

```{r}
# Further restrict taxa (drop F. praus, T. mob, E. coli) and samples
ps0 <- ps %>%
  subset_taxa(
    strain_group == "Inoculum" & 
    genus != "Faecalibacterium" &
    genus != "Escherichia" 
  ) %>%
  # Drop controls
  subset_samples(specimen_type %in% c("Fecal", "Inoculum")) %>%
  # Drop any other poorly-seq'd sample(s)
  prune_samples(sample_sums(.) > 1e3, .)
ntaxa(ps) - ntaxa(ps0)
sample_data(ps) %>% pull(specimen_type) %>% table
sample_data(ps0) %>% pull(specimen_type) %>% table
```

# try stuff

Can we calc bias relative to Bacteroides spp.?
<!-- Compute ratios -->

```{r}
# Compute ratios - after merging the Bacteroides
taxa <- c("Bacteroides ovatus", "Roseburia intestinalis", "Akkermansia muciniphila")
ps1 <- ps0 %>%
  prune_taxa(taxa, .)
# taxa_names(ps1) <- c("Bacteroides", taxa_names(ps1)[-1])
ps1.pw <- ps1 %>%
  pairwise_ratios(margin = "taxa", filter = FALSE) %>%
  pairwise_ratios(margin = "samples", filter = FALSE) %>%
  subset_samples(specimen_id.1 == specimen_id.2)
# taxa_names(ps1.pw)
pwtb <- ps1.pw %>%
  my_psmelt %>%
  rename(pair = taxon, bias = abundance) %>%
  separate(pair, c("taxon.1", "taxon.2"), sep = ":", remove = FALSE)
```

# Plot

```{r}
batch <- 2
pwtb %>%
  filter(
    # taxon.1 != "Bacteroides",
    taxon.1 != taxon.2,
    extraction_batch.1 == batch,
    center_id.1 == center_id.2,
    extraction_protocol.1 == "1",
    extraction_protocol.2 == "2",
  ) %>%
  ggplot(aes(
      x = specimen_type.1:center_id.1,
      y = bias, 
      color = center_id.1:specimen_type.1)) +
  geom_hline(yintercept = 1, color = "grey") +
  scale_y_log10() +
  scale_color_brewer(type = "qual", palette = "Paired", guide = "none") +
  facet_grid(taxon.1 ~ taxon.2, scales = "free_y") +
  # facet_grid(~ taxon.1) +
  labs(x = "{specimen type}:{extraction protocol}") +
  theme(
    axis.text.x = element_text(angle = 90)
  ) +
    geom_quasirandom(size = 0.5)
  # stat_summary(fun.data = fun.data, fatten = 1.8)
  # plot_annotation(
  #   title = str_glue(.sep = " ",
  #     "{prefix}Bias of Protocol 1:Protocol 2 in Batch {batch}"),
  #   subtitle = 
  #     str_c(sep = " ",
  #     "(row-taxon / col-taxon in aliquot extracted by P. 1)", "/",
  #     "(row-taxon / col-taxon in aliquot extracted by P. 2),",
  #     "for the same biological specimen")
  # )
```


Roseburia vs. Akkermansia

```{r}
batch <- 2
p1 <- pwtb %>%
  filter(
    taxon.1 == "Akkermansia muciniphila",
    taxon.2 == "Roseburia intestinalis",
    extraction_batch.1 == batch,
    center_id.1 == center_id.2,
    extraction_protocol.1 == "1",
    extraction_protocol.2 == "2",
  ) %>%
  ggplot(aes(
      x = specimen_type.1:center_id.1,
      y = bias, 
      color = center_id.1:specimen_type.1)) +
  geom_hline(yintercept = 1, color = "grey") +
  scale_y_log10() +
  scale_color_brewer(type = "qual", palette = "Paired", guide = "none") +
  labs(
    x = "{specimen type}:{sequencing center}",
    y = "Differential extraction bias",
    title = "Akkermansia muciniphila : Roseburia intestinalis"
    ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  ) +
  stat_summary(fun.data = mean_cl_boot, fatten = 1.8, size = 1) +
  geom_quasirandom(size = 1, alpha = 0.7)
p1
```


```{r}
batch <- 2
p2 <- pwtb %>%
  filter(
    taxon.1 == "Bacteroides ovatus",
    taxon.2 == "Roseburia intestinalis",
    extraction_batch.1 == batch,
    center_id.1 == center_id.2,
    extraction_protocol.1 == "1",
    extraction_protocol.2 == "2",
  ) %>%
  ggplot(aes(
      x = specimen_type.1:center_id.1,
      y = bias, 
      color = center_id.1:specimen_type.1)) +
  geom_hline(yintercept = 1, color = "grey") +
  scale_y_log10() +
  scale_color_brewer(type = "qual", palette = "Paired", guide = "none") +
  labs(
    x = "{specimen type}:{sequencing center}",
    y = "Differential extraction bias",
    title = "Bacteroides ovatus : Roseburia intestinalis"
    ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  ) +
  stat_summary(fun.data = mean_cl_boot, fatten = 1.8, size = 1) +
  geom_quasirandom(size = 1, alpha = 0.7)
p2
```

```{r}
p1 + p2
```


```{r}
ggsave(plot = p1, here("output/figures", "2020-10-26-amu-rin-batch2.pdf"),
  units = "in", width = 5, height = 4, scale = 1.3)
ggsave(plot = p2, here("output/figures", "2020-10-26-bov-rin-batch2.pdf"),
  units = "in", width = 5, height = 4, scale = 1.3)
```



# Figure 1: Extraction bias

```{r}
extraction_bias_plot <- function(batch, fun.data = NULL, prefix = "") {
  p <- pwtb0 %>%
    filter(
      extraction_batch.1 == batch,
      center_id.1 == center_id.2,
      extraction_protocol.1 == "1",
      extraction_protocol.2 == "2",
    ) %>%
    ggplot(aes(
        x = specimen_type.1:center_id.1,
        y = bias, 
        color = center_id.1:specimen_type.1)) +
    geom_hline(yintercept = 1, color = "grey") +
    scale_y_log10() +
    scale_color_brewer(type = "qual", palette = "Paired", guide = "none") +
    facet_grid(taxon.1 ~ taxon.2, scales = "free_y") +
    labs(x = "{specimen type}:{extraction protocol}") +
    theme(
      axis.text.x = element_text(angle = 90)
    ) +
    plot_annotation(
      title = str_glue(.sep = " ",
        "{prefix}Bias of Protocol 1:Protocol 2 in Batch {batch}"),
      subtitle = 
        str_c(sep = " ",
        "(row-taxon / col-taxon in aliquot extracted by P. 1)", "/",
        "(row-taxon / col-taxon in aliquot extracted by P. 2),",
        "for the same biological specimen")
    )
  if (is.null(fun.data)) {
    lyr <- geom_quasirandom(size = 0.5)
  } else {
    lyr <- stat_summary(fun.data = fun.data, fatten = 1.8)
  }
  # Note, must add text layer after due to continuous scale
  p + lyr + 
    geom_text(data = lbl, aes(x = 3.5, y = 1, label = label), color = "black")
}
```


```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 1, points
extraction_bias_plot("1", prefix = "Figure 1A. ")
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 1, mean est
extraction_bias_plot("1", fun.data = mean_cl_boot, "Figure 1B. ")
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 2, points
extraction_bias_plot("2", prefix = "Figure 1C. ")
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 2, mean est
extraction_bias_plot("2", fun.data = mean_cl_boot, "Figure 1D. ")
```


# Figure 2: Sequencing bias, S1:S2

```{r}
sequencing_bias_plot <- function(center1, center2, batch, fun.data = NULL,
  prefix = "") {
  p <- pwtb %>%
    filter(
      extraction_batch.1 == batch,
      extraction_protocol.1 == extraction_protocol.2,
      aliquot_number.1 == aliquot_number.2,
      center_id.1 == center1, 
      center_id.2 == center2,
      taxon.1 != taxon.2,
    ) %>%
    mutate(
      across(c(taxon.1, taxon.2), factor, levels = tree$tip.label),
      across(c(taxon.1, taxon.2), fct_relabel, tax_abbrev),
      # across(starts_with("extraction_protocol"), fct_relabel, ~str_c("P", .)),
    ) %>%
    ggplot(aes(
        x = specimen_type.1:extraction_protocol.1,
        y = bias, 
        color = extraction_protocol.1:specimen_type.1)) +
    geom_hline(yintercept = 1, color = "grey") +
    scale_y_log10() +
    # scale_color_brewer(type = "qual", palette = palettes["specimen_type"]) +
    scale_color_brewer(type = "qual", palette = "Paired", guide = "none",
      drop = FALSE) +
    facet_grid(taxon.1 ~ taxon.2, scales = "free_y") +
    labs(x = "{specimen type}:{extraction protocol}") +
    theme(
      axis.text.x = element_text(angle = 90)
    ) +
    plot_annotation(
      title = str_glue(.sep = " ",
        "{prefix}Bias of Center {center1}:Center {center2}", 
        "in Batch {batch}"),
      subtitle = str_glue(.sep = " ",
        "(row-taxon / col-taxon measured by {center1})", "/",
        "(row-taxon / col-taxon measured by {center2}),",
        "for the same DNA sample")
    )
  if (is.null(fun.data)) {
    lyr <- geom_quasirandom(size = 0.5)
  } else {
    lyr <- stat_summary(fun.data = fun.data, fatten = 1.8)
  }
  # Note, must add text layer after due to continuous scale
  p + lyr + 
    geom_text(data = lbl, aes(x = 2.5, y = 1, label = label), color = "black")
}

```


```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 1, points
sequencing_bias_plot("S1", "S2", "1", prefix = "Figure 2A. ")
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 1, mean est
sequencing_bias_plot("S1", "S2", "1", fun.data = mean_cl_boot, "Figure 2B. ")
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 2, points
sequencing_bias_plot("S1", "S2", "2", prefix = "Figure 2C. ")
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 2, mean est
sequencing_bias_plot("S1", "S2", "2", fun.data = mean_cl_boot, "Figure 2D. ")
```


# Figure 3: Sequencing bias, A1:S2



```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 1, points
sequencing_bias_plot("A1", "S2", "1", prefix = "Figure 3A. ") +
  geom_hline(data = gs_bias, aes(yintercept = gs_bias, color = "darkred"), alpha = 0.5)
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 1, mean est
sequencing_bias_plot("A1", "S2", "1", fun.data = mean_cl_boot, "Figure 3B. ") +
  geom_hline(data = gs_bias, aes(yintercept = gs_bias, color = "darkred"), alpha = 0.5)
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 2, points
sequencing_bias_plot("A1", "S2", "2", prefix = "Figure 3C. ") +
  geom_hline(data = gs_bias, aes(yintercept = gs_bias, color = "darkred"), alpha = 0.5)
```

```{r, include = TRUE, fig.dim = c(15, 15), out.dim = c(15, 15)}
# Batch 2, mean est
sequencing_bias_plot("A1", "S2", "2", fun.data = mean_cl_boot, "Figure 3D. ") +
  geom_hline(data = gs_bias, aes(yintercept = gs_bias, color = "darkred"), alpha = 0.5)
```


